### ISSUE TITLE
RuntimeError: mat1 dim 1 must match mat2 dim 0

### ISSUE THREAD

**Issue by hao-tian-ecnu** [rwickman/SparRL-PyTorch#1]
Hi Mr. Wickman,

Thanks for your good work! I'm trying to run your code with your given command but got a runtime error. I copy the output here, could you please help me solve this error?

Actually, before I meet this error. I have solved another two runtime errors.
1. File "/home/Code/SparRL-PyTorch/code/environment.py", line 137, in create_state
    local_stats = torch.log(local_stats + 1)
    RuntimeError: log_vml_cpu not implemented for 'Long'
     -I solved this error by adding 'dtype=torch.float32' in line 129 and line 132 environment.py
2.  File "/home/Code/SparRL-PyTorch/code/model.py", line 75, in forward
    src_node_embs = self.node_embs(node_ids.unsqueeze(2))
     RuntimeError: Expected tensor for argument #1 'indices' to have scalar type Long; but got torch.cuda.IntTensor instead (while checking arguments for embedding)
     - I solved this with below revision:
 		src_node_embs = self.node_embs(node_ids.long().unsqueeze(2))  Line 75 model.py
        	neigh_embs = self.node_embs(neighs.long())   Line 77 model.py

I'm not sure if my modification caused the error. Could you give me a help? Thanks!

Best,
Hao

~/Code/SparRL-PyTorch$ python3 code/main.py --edge_list graphs/karate/karate.edgelist --episodes 16000 --T_max 17 --save_dir karate_spearman_models/ --subgraph_len 32 --obj spearman
Making directed.
self.get_num_edges() 77
self._device cuda
Creating workers.
Making directed.
self.get_num_edges() 77
self._device cpu
e_i 0
T 5
/home/Code/SparRL-PyTorch/code/agents/agent.py:19: UserWarning: This overload of nonzero is deprecated:
	nonzero()
Consider using one of the following signatures instead:
	nonzero(*, bool as_tuple) (Triggered internally at  /opt/conda/conda-bld/pytorch_1603729128610/work/torch/csrc/utils/python_arg_parser.cpp:882.)
  return temp_subgraph.sum(axis=-1).nonzero().flatten()
e_i 1
T 8
e_i 2
T 16
e_i 3
T 9
e_i 4
T 5
e_i 5
T 11
e_i 6
T 9
e_i 7
T 5
e_i 8
T 14
e_i 9
T 9
e_i 10
T 4
e_i 11
T 14
e_i 12
T 3
e_i 13
T 2
e_i 14
T 10
e_i 15
T 4
e_i 16
T 8
  0%|                                                    | 0/16 [00:00<?, ?it/s]
Traceback (most recent call last):
  File "code/main.py", line 206, in <module>
    main(parser.parse_args())
  File "code/main.py", line 48, in main
    agent_man.run()
  File "/home/Code/SparRL-PyTorch/code/agent_manager.py", line 195, in run
    eval_reward = self._results_man.run_rl_eval(self._rl_agent, self.args.T_eval)
  File "/home/Code/SparRL-PyTorch/code/results_manager.py", line 110, in run_rl_eval
    edge_idxs = agent(state, argmax=True)
  File "/home/Code/SparRL-PyTorch/code/agents/rl_agent.py", line 468, in __call__
    q_vals = self._sparrl_net(state)
  File "/home/anaconda3/envs/SPARRL/lib/python3.6/site-packages/torch/nn/modules/module.py", line 727, in _call_impl
    result = self.forward(*input, **kwargs)
  File "/home/Code/SparRL-PyTorch/code/model.py", line 262, in forward
    node_embs = self.node_enc(state)
  File "/home/anaconda3/envs/SPARRL/lib/python3.6/site-packages/torch/nn/modules/module.py", line 727, in _call_impl
    result = self.forward(*input, **kwargs)
  File "/home/Code/SparRL-PyTorch/code/model.py", line 172, in forward
    torch.cat((node_embs, local_stats), -1)))
  File "/home/anaconda3/envs/SPARRL/lib/python3.6/site-packages/torch/nn/modules/module.py", line 727, in _call_impl
    result = self.forward(*input, **kwargs)
  File "/home/anaconda3/envs/SPARRL/lib/python3.6/site-packages/torch/nn/modules/linear.py", line 93, in forward
    return F.linear(input, self.weight, self.bias)
  File "/home/anaconda3/envs/SPARRL/lib/python3.6/site-packages/torch/nn/functional.py", line 1692, in linear
    output = input.matmul(weight.t())
RuntimeError: mat1 dim 1 must match mat2 dim 0

**Comment by rwickman** [comment]
Yeah I would change it back. I did not mention in the README.md, which is my fault, but you need to have PyTorch + CUDA installed

**Comment by hao-tian-ecnu** [comment]
Thank you for your reply! I have tried to create a new torch with cuda environment using anaconda. The number 1 and 2 error did not occur, so it's my environment problem. However, the runtime error 'RuntimeError: mat1 dim 1 must match mat2 dim 0' is still there. I create env with pytorch 1.8.0, cuda 11.1.

**Comment by rwickman** [comment]
Decided to run the code with what I had in the README.md. Turns out I forgot to put `--T_eval 32 --eval_batch_size 1`, this specifies that I want to prune 32 edges when evaluating and only prune one batch of edges at a time. The default, which works for larger graphs that I tested in the paper, was trying to prune more batches of edges than what was in the graph (e.g., 32 * 8 is more than the number of edges in karate).

Regardless, the README.md now has the correct commands. Sorry for the confusion!

**Comment by hao-tian-ecnu** [comment]
Thank you so much! The training command works, but the evaluation command has the same error. I also add `--T_eval 32 --eval_batch_size 1` to the end of the evaluation command and it works.
